server:
  address: '192.168.1.106'
  port: 8080
  servlet:
    context-path: '/api'
logging:
  level:
    org.springframework: ERROR #DEBUG,ERROR,INFO,WARN

spring:
  application:
    name: 'api-app-compras'